name: Build and Push to GHCR

on:
  push:
    branches: [main]

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/slippc-arrow-base
  GHCR_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Arrow base image
        run: |
          docker build --platform=linux/amd64 -t ghcr.io/sweber35/slippc-arrow-base:latest .
          docker push ghcr.io/sweber35/slippc-arrow-base:latest
