name: Build Arrow Base Image

on:
  push:
    branches:
      - main

jobs:
  build-arrow-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Arrow base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.arrow
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/slippc-arrow-base:latest
